import type { Metadata } from "next";

import "./globals.css";

// import Head from "next/head";

export const metadata: Metadata = {
  title: "Whack A Mole",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        {children}
      </body>
    </html>
  );
}
